services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    environment:
      - EULA=TRUE 
      - VERSION=1.21.4
    ports:
      - "25565:25565" 
    volumes:
      - ./minecraft_data:/data
    restart: unless-stopped
